### ISSUE TITLE
Monoid laws seems broken

### ISSUE THREAD

**Issue by Badmoonz** [vmchale/permutations#2]
```    describe "monoid laws" $ do
      it "Neutral (1/2)" $ do
        trivial <+> neutral `shouldBe` neutral <+> trivial

      it "Neutral (2/2)" $ do
        circ <+> neutral `shouldBe` neutral <+> circ      ```

Second test fails

**Comment by vmchale** [comment]
Hi,

Thanks for the bug report! I'm not actually sure that this is a problem with the monoid instance rather than the multiplication. I don't quite have time to investigate in the near future, so any pull requests to fix this would be welcome :)

**Comment by vmchale** [comment]
Should be fixed now, added a test case :)
